feat: add access key into environment
lablup/backend.ai-manager pull request #437
Opened 2021-06-11 16:21 UTC by lizable

This PR adds each user's own access key as an environment variable called 'BACKENDAI_ACCESS_KEY'.

2021-06-12 03:13 UTC, adrysn requested changes
Just a minor request for an update.

2021-06-12 03:13 UTC, adrysn commented on src/ai/backend/manager/registry.py
> +            'BACKENDAI_ACCESS_KEY': scheduled_session.access_key
Please append a trailing comma for better diff readability.

2021-06-12 03:13 UTC, adrysn commented on src/ai/backend/manager/registry.py
> +                                'BACKENDAI_ACCESS_KEY': scheduled_session.access_key
Same here.

2021-06-12 03:13 UTC, adrysn commented on changes/437.feature
> +Add a environment variable `BACKENDAI_ACCESSKEY` for identifying the owner of the session
`BACKENDAI_ACCESSKEY` -> `BACKENDAI_ACCESS_KEY`

2021-06-13 03:56 UTC, achimnol requested changes
Setting the env-vars in `start_session()` applies to all kernels (containers) in the same (cluster) session (e.g., `cluster_size`), while doing so in `create_kernels_in_one_agent()` applies to individual kernels (e.g., `cluster_idx`). So the second assignment of `BACKENDAI_ACCESS_KEY` is a duplicate. Please remove it.

2021-06-13 05:38 UTC, merged