feat: provide schedulable status of agent
lablup/backend.ai-manager pull request #500
Opened 2021-12-03 15:10 UTC by lizable

This PR provides the mutation query of agent setting.
For now, the user with superadmin role can update `schedulable` value only.

Related PR: [backend.ai-webui#1167](https://github.com/lablup/backend.ai-webui/pull/1167).

2021-12-04 05:12 UTC, adrysn requested changes
Let's make `schedulable` input optional.

2021-12-04 05:12 UTC, adrysn commented on src/ai/backend/manager/models/agent.py
> +    schedulable = graphene.Boolean(required=True, default=True)
Let's make this field optional. Other fields of the `agents` table should be updated without altering the value of `schedulable`. For example, I want to add another mutable field, `scaling_group` here, in a separate issue in the near future.

2021-12-05 06:41 UTC, adrysn approved these changes
LGTM. @achimnol, please double-check and merge if you are okay.

2021-12-09 07:40 UTC, achimnol approved these changes
LGTM!

2021-12-09 07:42 UTC, merged