feat: implement image metadata related GraphQL mutations
lablup/backend.ai-manager pull request #568
Opened 2022-04-01 07:57 UTC by kyujin-cho

This PR implements `clean_images` and `modify_image` mutations.
- `clean_images`: removes all image (and image aliases, of course) records from database
- `modify_image`: update image metadata records on database. Check `ModifyImageInput` inside `image.py` for supported fields.

2022-04-03 03:15 UTC, achimnol requested changes

2022-04-03 03:15 UTC, achimnol commented on src/ai/backend/manager/models/image.py
> +        log.info('clear all images by API request')
We arleady have `GQLLoggingMiddleware`. Please remove unncessary logs.

2022-04-03 03:15 UTC, achimnol commented on src/ai/backend/manager/models/image.py
> +        log.info('modify image(ref: {0}) by API request', target)
Same here.

2022-04-04 05:35 UTC, adrysn commented
I tested this PR with the Control-Panel, and works as I expected.

2022-04-05 08:18 UTC, achimnol approved these changes

2022-04-05 08:19 UTC, merged