feat: Add `KeyPairResourcePolicy.max_session_lifetime`
lablup/backend.ai-manager pull request #583
Opened 2022-04-21 09:26 UTC by achimnol

resolves lablup/backend.ai-internal#46

2022-04-21 09:35 UTC, achimnol commented
TODO: add a timer to periodically check expired sessions

2022-04-24 13:02 UTC, adrysn requested changes
I found an error in `SessionlifetimeChecker. Other parts seem to be working well in my test environment.

2022-04-24 13:02 UTC, adrysn commented on src/ai/backend/manager/idle.py
> +            if now - session["created_at"] >= policy["max_session_lifetime"]:
If `max_session_lifetime` is zero, I suggest interpreting it as infinity. Also, these lines raise exceptions due to calculation type-mismatch issues. These might be updated to something like below:

```python
now = await dbconn.scalar(sa.select(sa.func.now()))
if policy["max_session_lifetime"] > 0:
    # TODO: once per-status time tracking is implemented, let's change created_at
    #       to the timestamp when the session entered PREPARING status.
    if now - session["created_at"] >= timedelta(seconds=policy["max_session_lifetime"]):
```

2022-04-25 01:15 UTC, adrysn approved these changes
Tested and LGTM.

2022-04-25 01:19 UTC, merged